# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# TODO: put pipeline in a directory called /.azure-pipelines (this matches what they are doing in Azure)
# TODO: rename this pipeline to something useful
# Get files from the dev branch
# Validate file and content format.
# Stage files that contain GE samples into an artifact staging directory. Make sure that the files are in the expected format.
# TODO: learn how to copy files to blob storage froom Azure pipeline
# Copy files to Azure blob storage using service connection. (connect with Michael to do this)