# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include: 
    - dev 

pool:
  vmImage: 'ubuntu-latest'

# Get files from the dev branch
# Validate file and content format.
# Stage files that contain GE samples into an artifact staging directory. Make sure that the files are in the expected format.
# Copy files to blob storage from Azure pipeline - 
# Copy files to Azure blob storage using service connection. (connect with Michael to do this, will use the devxapistorage) using the Azure File Copy task

steps:
- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: |
      **/permissions/** 
      **/sample-queries/**
    TargetFolder: '$(build.artifactstagingdirectory)'
   
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.ArtifactStagingDirectory)' 
     
